### ISSUE TITLE
Is it okay and if there is a recommended way to use RxJS with realar?

### ISSUE THREAD

**Issue by bangonkali** [betula/realar#102]
Hi, awesome work so far. I've been using it for a few hours now and I like the concept. Unfortunately I needed more complex ways of filtering, debouncing and managing multiple eventsources do you think it's okay and do you have a recommended way of using RxJS with this project?

**Comment by betula** [comment]
Thanks a lot for your time!
Of course, you are absolutely right, there are not enough streaming operations at the moment. I plan to implement more advanced work with streams in the next releases so that it would be possible to migrate from RxJS.

In the examples below, you can see how to use Realar together with RxJS, but for the best possibilities, I want to implement everything you need inside Realar soon.

[play on runkit](https://runkit.com/betula/60e9478b16dd870013fb9eaf)
```javascript
import { Observable, Subject } from 'rxjs';
import { signal } from 'realar';


const signalFromSubject = (subj) => {
  const sig = signal();
  subj.subscribe({ next: sig });
  return sig;
}
const signalToSubject = (sig) => { // valueToSubject will be same
  const subj = new Subject();
  sig.to((v) => subj.next(v));
  return subj;
}
const signalToObservable = (sig) => { // valueToObservable will be same
  return new Observable(subscriber => {
    sig.to((v) => subscriber.next(v));
  });
}


// Examples

// make an instance of RxJS Subject
const subj = new Subject();

// make Realar signal from RxJS Subject
const sig = signalFromSubject(subj).to(v => console.log(`signal: ${v}`));

// make RxJS Subject from Realar signal
const sig_subj = signalToSubject(sig);
sig_subj.subscribe({ next: (v) => console.log(`signal subject: ${v}`) });

// make RxJS Observable from Realar signal
const sig_obs = signalToObservable(sig);
sig_obs.subscribe((v) => console.log(`signal observable: ${v}`));


// Try It

subj.next(10);
// console output:
// signal: 10
// signal subject: 10
// signal observable: 10
```
[play on runkit](https://runkit.com/betula/60e9478b16dd870013fb9eaf)

Thank you for helping me make the world a better place!
